language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g npm@latest
  - rm -rf node_modules
  - npm install
  - npm install -g firebase-tools

script:
  # TODO: run tests
  - cd www && npm run build && cd ..

after_success:
  - firebase deploy --only hosting --token=${FIREBASE_TOKEN}
