language: node_js
node_js:
  - "5.11"

env:
  global:
    - CI=false

branches:
  only:
    - master

before_script:
  - npm install -g npm@latest
  - rm -rf node_modules
  - cd www && npm install && cd ..
  - cd functions && npm install && cd ..
  - npm install -g firebase-tools

script:
  # TODO: run tests
  - set CI=false 
  - cd www && npm run build && cd ..

after_success:
  - firebase deploy --only hosting --token=${FIREBASE_TOKEN}
